### ISSUE TITLE
RJCLI certain commands are not working

### ISSUE THREAD

**Issue by Akash1713** [rjainoje/rjcli#6]
![image](https://user-images.githubusercontent.com/42678757/147545965-73c70a74-f986-4456-9238-cb23babd6f7a.png)
dellemc-ppdm-cli > show --jobs failed --period 1day-ago
Traceback (most recent call last):
  File "rjcli.py", line 83, in get_activities
  File "site-packages\requests\models.py", line 941, in raise_for_status
requests.exceptions.HTTPError: 500 Server Error:  for url: https://10.20.20.20:8443/api/v2/activities?filter=classType+in+%28%22JOB%22%2C+%22JOB_GROUP%22%29+and+category+eq+%22PROTECT%22+and+createdTime+gt+%222021-12-26T22%3A41%3A33.038276%22+and+state+in+%28%22COMPLETED%22%29+and+result.status+in+%28%22FAILED%22%2C+%22CANCELED%22%29&orderby=createTime+DESC&pageSize=10000

**Comment by rjainoje** [comment]
There seem to be a change in time format, looks like api was not accepting an earlier format, its now been corrected and working well. Let me know if you have any issues.

PS. I have added a command called alerts to manage alerts in bulk
